### PR TITLE
Bt updates

### LINKED ISSUE #2358: Subsurface Mobile "Show all bluetooth devices..." is not sticky over reboots
### Describe the issue:
- [ x] Bug
After a reboot, the bluetooth setting "Show all devices..." is unchecked.

### Issue long description:

In order to get a list of bluetooth devices to show up in the download screen you may need to enable this option. All known bluetooth devi ec then appear in the connection list. After a reboot of the phone, this option is turned off and no bluetooth devices appear in the connection list.

Note that in my world none of the bluetooth devices were "recognized" dive computers. this is a secondary issue. the real problem is that the option turned itself off, leading to inconsistent behaviour for the end user.
 
### Operating system:

Android 10

Essential PH-1

### Subsurface version:

Subsurface mobile 2.2.2 (4.9.3.119)

Subsurface mobile downloaded from android store thingy

### Steps to reproduce:

set the option
restart phone
option is no longer set...
### Expected behavior:

Option should be retained over restarts

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

two small fixes.
One subtle update to the detection code for the OSTC family of computers - picking OSTC 3 ended up causing us to not recognize certain BLE versions of the OSTC on iOS as dive computers.
And a change to the language on the settings page that clarifies that the "show all BT devices" settings is not persistent.

### Related issues:

Fixes #2358 

### Release note:

done

### CODE REVIEW

**Comment by Subsurface-divelog** [comment]
@glance- since you know the OSTC family of dive computers better than I do... does this seem reasonable to you? This code will only run if the dive computer was detected, so we should only assign vendor/product pairs that will then show up as available, i.e. we need too pick BT/BLE enabled products...

File: core/btdiscovery.cpp [hunk 1]
```diff
@@ -31,8 +31,8 @@ static dc_descriptor_t *getDeviceType(QString btName)
 		else if (btName.mid(4,2) == "2-") product = "OSTC 2N";
 		else if (btName.mid(4,2) == "+ ") product = "OSTC 2";
 		// all OSTCs are HW_FAMILY_OSTC_3, so when we do not know,
```
Comment (glance-) [inline core/btdiscovery.cpp]: This comment isn't that correct. Not all OSTC's are HW_FAMILY_OSTC_3, but, rather, all with bluetooth are HW_FAMILY_OSTC_3.

Comment (glance-) [reply core/btdiscovery.cpp]: But, there's also the Frog, which is a HW computer with bluetooth, which isn't a HW_FAMILY_OSTC_3, but there weren't that many of them made, and I've actually never seen one, so lets ignore that =)

File: core/btdiscovery.cpp [hunk 2]
```diff
@@ -31,8 +31,8 @@ static dc_descriptor_t *getDeviceType(QString btName)
...
-		// just try this
-		else product = "OSTC 3"; // all OSTCs are HW_FAMILY_OSTC_3
```
Comment (glance-) [inline core/btdiscovery.cpp:35]: Yea, the "OSTC 3" didn't have bluetooth, so thats probably why it fell away somewhere along the way. The "OSTC Plus" (3+) all as bluetooth.

**Comment by glance-** [comment]
Looks reasonable. I commented about some odds and ends to try to clarify things.

**Review by glance- — APPROVED** [review]

File: core/btdiscovery.cpp (hunk 2 above)
Comment (Subsurface-divelog) [reply core/btdiscovery.cpp:35]: I kept it as "OSTC 2" as the default product name = I saw no advantage naming it "OSTC Plus"
But I updated the comment to be clearer.

File: core/btdiscovery.cpp (hunk 1 above)
Comment (Subsurface-divelog) [reply core/btdiscovery.cpp]: I had one conversation with a Frog owner a few years ago... but yes, they are being ignored here because I don't even know the BT name... :-)
