### PR TITLE
Fix possible memory corruption

### LINKED ISSUE #507: Crash when downloading from Mares M1 dive computer
I'm download dive logs from Mares M1 via PC interface.
By reaching 100 % the application crashes.
Subsurface: 4.6.4-1
Environment: Ubuntu 16.04 x64

No crash if I check "save dump file of libdivecomputer".

Do you need some more information or dumps?
[Log und Dump.zip](https://github.com/Subsurface-divelog/subsurface/files/1173261/Log.und.Dump.zip)

### PR DESCRIPTION
**Pull request by janmulder**
Version 2: 

A user reports a SIGSEGV that points to DownloadFromDCWidget::updateProgressBar() in relation to strlen()/strdup(), at end of download. Reading the code, as I can't reproduce the crash, it seems that the progress_bar_text is set to NULL and later strdup-ped. The man page is not fully clear on this, but setting it
to the empty strings is much safer.

Might fix: #507

Signed-off-by: Jan Mulder <jlmulder@xs4all.nl>

### CODE REVIEW

File: desktop-widgets/downloadfromdivecomputer.cpp [hunk 1]
```diff
@@ -116,7 +116,8 @@ void DownloadFromDCWidget::updateProgressBar()
 		ui.progressBar->setFormat("%p%");
 	}
 	ui.progressBar->setValue(lrint(progress_bar_fraction * 100));
-	free(last_text);
+	if (last_text)
```
Comment (dirkhh) [inline desktop-widgets/downloadfromdivecomputer.cpp]: From the man page:
The free() function deallocates the memory allocation pointed to by ptr. If ptr is a NULL pointer, no operation is performed.
So passing NULL to free is valid. The only way this could crash was if something else free'ed last_text...
Based on that I'd say your commit doesn't look like the correct fix to me.

**Review by dirkhh — CHANGES_REQUESTED** [review]

File: desktop-widgets/downloadfromdivecomputer.cpp (hunk 1 above)
Comment (janmulder) [reply desktop-widgets/downloadfromdivecomputer.cpp]: ok, ignore this. You are right.

File: desktop-widgets/downloadfromdivecomputer.cpp [hunk 2]
```diff
@@ -116,7 +116,8 @@ void DownloadFromDCWidget::updateProgressBar()
...
+		free(last_text);
 	last_text = strdup(progress_bar_text);
```
Comment (dirkhh) [inline desktop-widgets/downloadfromdivecomputer.cpp]: the crash in #507 is in strdup... is it possible that calling strdup on NULL is what causes the crash?
