### PR TITLE
Translate header strings for APD

### LINKED ISSUE #3246: Import Logfile nor properly initialized
### Describe the issue:
- [ ] Bug

### Issue long description:
When calling the dialog from the menu and after selecting the file to be imported (in my case a .apd file APD - Log Viewer ) the dialog shows in the selection combobox APD - Log Viewer - DC1 what is correct, but the fields are not initialized with the given tags for APD files - the fields are shown like "Manual import".
So i have to select another import type from the combobox and tags switch back to "APD - Log Viewer - DC1" than it shows the proper tags for the fieldlist.
When changing the language in subsurface to english (UK) the dialog is properly initialized!

### Operating system:
Windows 10 latest version german language

### Subsurface version:
Subsurface 5.0.1
official release / installer

### Steps to reproduce:
1, menu "Import"
2. click "import log files"
3. select a *.apd file"
4. check combobox and field - tags.
5. change subsurface language to german and repeat the steps.
6. change subsurface language to english (UK) and repeat the steps.

[08D006582_210228_085648.zip](https://github.com/subsurface/subsurface/files/6458787/08D006582_210228_085648.zip)

### Current behavior:
dialog depending on the language initialized.

### Expected behavior:
dialog initialized language independend and properly.

### PR DESCRIPTION
**Pull request by atdotde**
We are matching translated header names. Thus, when composing
a header line for APD, make sure it contains translations.

This mechanism is quite brittle. Our German translations had
two different translations for "Sample time" and this already
broke it. This is why this patch also includes a fix for a
translation string (should be fixed in transiflex as well
of course).

Fixes #3246

Signed-off-by: Robert C. Helling <helling@atdotde.de>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

File: desktop-widgets/divelogimportdialog.cpp [hunk 1]
```diff
@@ -573,7 +573,7 @@ void DiveLogImportDialog::loadFileContents(int value, whatChanged triggeredBy)
 
 		apd=true;
 
-		firstLine = "Sample time" + apdseparator + "Sample depth" + apdseparator + "Sample setpoint" + apdseparator + "Sample sensor1 pO₂" + apdseparator + "Sample sensor2 pO₂" + apdseparator + "Sample sensor3 pO₂" + apdseparator + "Sample pO₂" + apdseparator + "" + apdseparator + "" + apdseparator + "" + apdseparator + "" + apdseparator + "" + apdseparator + "" + apdseparator + "" + apdseparator + "" + apdseparator + "Sample temperature" + apdseparator + "" + apdseparator + "Sample CNS" + apdseparator + "Sample stopdepth";
+		firstLine = tr("Sample time") + apdseparator + tr("Sample depth") + apdseparator + tr("Sample setpoint") + apdseparator + tr("Sample sensor1 pO₂") + apdseparator + tr("Sample sensor2 pO₂") + apdseparator + tr("Sample sensor3 pO₂") + apdseparator + tr("Sample pO₂") + apdseparator + "" + apdseparator + "" + apdseparator + "" + apdseparator + "" + apdseparator + "" + apdseparator + "" + apdseparator + "" + apdseparator + "" + apdseparator + tr("Sample temperature") + apdseparator + "" + apdseparator + tr("Sample CNS") + apdseparator + tr("Sample stopdepth");
```
Comment (dirkhh) [inline desktop-widgets/divelogimportdialog.cpp:576]: we typically try to explicitly NOT compare translated strings because that's so bleeping fragile.
I see how this is a temporary fix, but it's just bound to fail again...

**Review by dirkhh — APPROVED** [review]
ugh. brittle indeed. But better than current state, I guess
