### PR TITLE
fix weights rounding

### LINKED ISSUE #532: qthelper#weight_string invalid rounding
I noticed this when inputting weights:

"22lbs" --> 9.10kg, rather than 9.98 (or potentially just 10kg).

This is on desktop, version 4.6.4.

### PR DESCRIPTION
**Pull request by janmulder**
Simplify and fix presentation of weights. Due to the attempt to round only the grams part (by just adding 50 to it, and truncating afterwards) a weird effect was introduced. For example, a value 0.98 was presented as 0.10. Just replay the old logic, and see what happens. Rewrote the logic to a simpler and better one.

fixes: #532

Signed-off-by: Jan Mulder <jlmulder@xs4all.nl>

### CODE REVIEW

File: core/qthelper.cpp [hunk 1]
```diff
@@ -43,12 +43,8 @@ QString weight_string(int weight_in_grams)
...
 	QString str;
 	if (get_units()->weight == units::KG) {
-		int gr = weight_in_grams % 1000;
-		int kg = weight_in_grams / 1000;
-		if (kg >= 20.0)
-			str = QString("%1").arg(kg + (gr >= 500 ? 1 : 0));
-		else
-			str = QString("%1.%2").arg(kg).arg((unsigned)(gr + 50) / 100);
+		double kg = (double) weight_in_grams / 1000.0;
+		str = QString("%1").arg(kg, 0, 'f', kg >= 20.0 ? 0 : 1);
```
Comment (dirkhh) [inline core/qthelper.cpp:47]: but that doesn't round at all... and will print 1.99kg as 1.9kg when it really should be 2.0kg
Yes, it's MORE correct than the bogus logic we have right now (so I'll take it), but I'd love a follow up that correctly rounds (and yes, that's a bit tricky with our odd 20kg threshold - I'm sure you can do this :-) )
