### PR TITLE
map-widget: don't crash if the map QML failed to load

### LINKED ISSUE #596: [BUG] googlemaps: don't crash when the plugin isn't loaded
https://github.com/Subsurface-divelog/subsurface/issues/589

If the plugin isn't loaded due to a missing plugin binary or qt-location modules, attempt to not crash when calling QML code from C++.

Also, either show an error message in the map-widget (1) or hide the widget completely (2).
My vote is for (1).

@dirkhh

### PR DESCRIPTION
**Pull request by neolit123**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

If the QML modules for QtLocation and QtPositioning are
missing the QML in mapwidget.cpp will fail to load,
which can lead to crashes.

To solve the issue check if the QML has loaded and set
a flag 'isReady' to true. If the loading has failed
load another QML which is for showing a red error text
in the lines of `MapWidget.qml failed to load!`.

If the map QML has failed, use a macro in all relevant
MapWidget members to turn them into a NOP. This approach
leaves the rest of the codebase intact - e.g. no checks
in classes which connect to the MapWidget class.

### Changes made:

1) added a new small QML file for the purpose of showing an error message
2) made fixes in mapwidget.cpp

### Related issues:

Fixes #596

### Additional information:

none

### Mentions:

@dirkhh @mturkia @sfuchs79

### CODE REVIEW

**Comment by mturkia** [comment]
Works on my test without crashing (removed the libqtgeoservices_googlemaps.so).

File: desktop-widgets/mapwidget.cpp [hunk 1]
```diff
@@ -22,19 +28,23 @@ MapWidget::MapWidget(QWidget *parent) : QQuickWidget(parent)
 	qmlRegisterType<MapLocationModel>("org.subsurfacedivelog.mobile", 1, 0, "MapLocationModel");
 	qmlRegisterType<MapLocation>("org.subsurfacedivelog.mobile", 1, 0, "MapLocation");
 
+	setResizeMode(QQuickWidget::SizeRootObjectToView);
 	connect(this, &QQuickWidget::statusChanged, this, &MapWidget::doneLoading);
-	setSource(QUrl(QStringLiteral("qrc:/MapWidget.qml")));
+	setSource(QUrl(urlMapWidget));
```
Comment (dirkhh) [inline desktop-widgets/mapwidget.cpp]: urlMapWidget is a QUrl - so why are you creating a new QUrl from it?

**Review by dirkhh — COMMENTED** [review]
I really like this otherwise - just the one question about the QUrl.

**Comment by dirkhh** [comment]
please see #647 instead

File: desktop-widgets/mapwidget.cpp (hunk 1 above)
Comment (neolit123) [reply desktop-widgets/mapwidget.cpp]: i will fix this.

**Comment by neolit123** [comment]
made the small `QUrl` update.

this is unrelated to #647 BTW.
i've closed my other PR attempt to fix the dive-sites.

**Comment by dirkhh** [comment]
Sorry, @neolit123 - I clearly had too many tabs open last night. Yes, this has nothing to do with #647
