### PR TITLE
QML UI: Parse multiple buddies when editing a dive

### LINKED ISSUE #168: Handling of multiple buddies in Subsurface-mobile is still broken
This is with 1.2.0(4.6.0.22) tested on iOS on an iPad Pro 9.6"
a) you can edit the text "Multiple Buddies" and then that becomes your buddy
b) when editing multiple dives one after another, Subsurface-mobile showed me the two buddies from the previous dive after I saved a dive. Switching dives fixed that second problem

There are two ways to go with this:
(1) easy fix - make "Multiple Buddies" read only
(2) real fix - make it truly handle edits to multiple buddies; at least some of the obvious cases - and if that algorithm gets confused, restore the previous buddies (after showing a warning)

### PR DESCRIPTION
**Pull request by jbygdell**
This allows the user to enter multiple buddies as a comma separated list,
the "Multiple Buddies" entry is still a special case as we can only populate
the combobox with a single name for each entry.

fixes #168

Signed-off-by: Joakim Bygdell <j.bygdell@gmail.com>

### CODE REVIEW

File: mobile-widgets/qmlmanager.cpp [hunk 1]
```diff
@@ -869,13 +869,11 @@ void QMLManager::commitChanges(QString diveId, QString date, QString location, Q
...
 	}
 	if (myDive->buddy() != buddy) {
-		if (myDive->buddy().contains(",")) {
-			if (!buddy.contains(tr("Multiple Buddies"))) {
-				diveChanged = true;
-				free(d->buddy);
-				d->buddy = strdup(qPrintable(buddy));
-			}
-		} else {
+		if (buddy.contains(",") && !buddy.contains(QRegExp("(,\\s)"))){
```
Comment (dirkhh) [inline mobile-widgets/qmlmanager.cpp]: So this triggers on a list of buddies that doesn't have a space after a comma, right? I'm not quite sure why the regex has the parenthesis... can you explain this a bit more?
But for example, "Linus,Joe, John" will pass that condition

File: mobile-widgets/qmlmanager.cpp [hunk 2]
```diff
@@ -869,13 +869,11 @@ void QMLManager::commitChanges(QString diveId, QString date, QString location, Q
...
+			QStringList tempList = buddy.split(',');
+			buddy = tempList.join(", ");
+		}
```
Comment (dirkhh) [inline mobile-widgets/qmlmanager.cpp:874]: and then it re-assembles them with an additional space after the comma, so my list from before becomes "Linus, Joe,  John" with two spaces before "John". Is that what you wanted? And why?

File: mobile-widgets/qmlmanager.cpp [hunk 3]
```diff
@@ -1436,14 +1434,9 @@ QStringList QMLManager::buddyInit() const
 	int i = 0;
 	for_each_dive (i, d) {
 		QString temp = d->buddy;
-		if (!temp.isEmpty() && !temp.contains(",")){
+		if (!temp.isEmpty()){
 			buddies << d->buddy;
 		}
```
Comment (dirkhh) [inline mobile-widgets/qmlmanager.cpp:1438]: this now pushes the string with the commas into buddies (which is a QStringList) - that's not what you want, is it?
See two comments below

File: mobile-widgets/qmlmanager.cpp [hunk 4]
```diff
@@ -1436,14 +1434,9 @@ QStringList QMLManager::buddyInit() const
...
-		else if (!temp.isEmpty()){
-			QRegExp sep("(,\\s)");
```
Comment (dirkhh) [inline mobile-widgets/qmlmanager.cpp:1443]: I guess this is where the regex with the parenthesis came from?

File: mobile-widgets/qmlmanager.cpp [hunk 5]
```diff
@@ -1436,14 +1434,9 @@ QStringList QMLManager::buddyInit() const
...
-			QStringList tempList = temp.split(sep);
-			buddies << tempList;
-		}
```
Comment (dirkhh) [inline mobile-widgets/qmlmanager.cpp:1446]: Because this is what you actually want, you want buddies to hold a list of the buddies

**Review by dirkhh — CHANGES_REQUESTED** [review]
Thanks for the pull request... I won't take these changes as they get things wrong in a few rather common scenarios (see my comments in the code) - and because I think the right fix goes a little further...

I think we should completely remove the "Multiple Buddies" magic and just show the list of buddies. If after editing we get something back without a comma, things are easy. If we get something back with comma(s), then clean things up so that "\\s*,\\s*" gets converted to ", " (comma and one space on the right) and then split the string at the commas/space when you updated buddies.

Does that make sense?

File: mobile-widgets/qmlmanager.cpp (hunk 3 above)
Comment (jbygdell) [reply mobile-widgets/qmlmanager.cpp:1438]: This is the initial list creation when reading the divelog, if there is a dive in the divelog that has more than one buddy it is already a list. In which case it just adds to the big list of buddies.

File: mobile-widgets/qmlmanager.cpp (hunk 1 above)
Comment (jbygdell) [reply mobile-widgets/qmlmanager.cpp]: In order for the outcome to be correct the string that is actually saved to the logbook needs to have a space after the comma or they will be saved as one. In your example above you would get two buddies, "Linus,Joe" and "John".
So we might end up having to split on all commas then add a check to see if the first character is a space or not, if it is not a space add one when reassembling the string.

File: mobile-widgets/qmlmanager.cpp (hunk 3 above)
Comment (dirkhh) [reply mobile-widgets/qmlmanager.cpp:1438]: I'm not sure you are correct. d->buddy is a "char *", so by removing this check you now add "Linus, Joe, John" as one completion to the drop down. I'm not saying that's necessarily wrong - it's just a bit confusing if you dive with a lot of different combinations of partners. The existing code instead took the string apart and added each buddy individually. I think :-)

File: mobile-widgets/qmlmanager.cpp (hunk 1 above)
Comment (dirkhh) [reply mobile-widgets/qmlmanager.cpp]: See my comment in the overall review above. We need to convert "\\s*,\\s*" into ", " for this all to work as intended. That could be done with a single QString replace that uses exactly that regex and replaces it every time it finds it. My comment simply pointed out that the way that you wrote the code, we could end up with extra spaces in front of buddy names and then you'd suddenly have "John" and " John" in your list of buddies - and that would be confusing.

File: mobile-widgets/qmlmanager.cpp (hunk 3 above)
Comment (jbygdell) [reply mobile-widgets/qmlmanager.cpp:1438]: That char * get converted into a QString and when you have a QString with ", " in it, and add that to a QStringList it apparently get parsed as a list. Or some other magic happens as I did not see any list entries with more than one name on it.
But since the existing code works it can stay.

File: mobile-widgets/qmlmanager.cpp (hunk 1 above)
Comment (jbygdell) [reply mobile-widgets/qmlmanager.cpp]: if (buddy.contains(",")){
	buddy = buddy.replace(QRegExp("\\s*,\\s*"), ", ");
}

This appears to do the trick.

**Comment by jbygdell** [comment]
v2.0

**Comment by dirkhh** [comment]
This is much better. I understand why you show "Multiple Buddies" instead of showing the actual buddies - that's something that I'd love to figure out how to fix, but this definitely makers things better already, so I'll pull it. Thanks
